# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccountVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.IntegerField(default=0)),
                ('knocked', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('state_house', models.IntegerField(default=0)),
                ('state_senate', models.IntegerField(default=0)),
                ('us_house', models.IntegerField(default=0)),
                ('us_senate', models.IntegerField(default=0)),
                ('school_board', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
        migrations.AddField(
            model_name='accountvoter',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Voter'),
        ),
    ]
