# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='street1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='street2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='us_house',
            new_name='congress',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='active',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='us_senate',
        ),
        migrations.AddField(
            model_name='voter',
            name='county',
            field=models.CharField(default='ORA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 7, 23, 13, 57, 625646, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='dob',
            field=models.CharField(default='0/0/0000', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='exempt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='extra_suffix',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='group',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_address1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_address2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_city',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_country',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_state',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_zipcode',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='middle_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='precinct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='race',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='registration',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='split',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='suffix',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 7, 23, 15, 21, 166543, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='voterID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(max_length=5),
        ),
    ]
