# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160507_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='signature',
            field=models.BooleanField(default=False),
        ),
    ]
