# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160515_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
