# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180805_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voterID',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
