# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-07 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voterlatlongexception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='signature',
        ),
        migrations.AddField(
            model_name='voter',
            name='county_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='mailing_address3',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
