# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180809_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='congress',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='county',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='county_commission',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='race',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='school_board',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_house',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_senate',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
