# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-11 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180809_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='county',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='latitude',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='longitude',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
